# QuickPage Configuration
neuprint:
  server: "neuprint.janelia.org"
  dataset: "optic-lobe:v1.1"
  # server: "neuprint-cns.janelia.org"
  # dataset: "cns"

output:
  directory: "output"
  template_dir: "templates"
  # Additional output settings
  include_3d_view: true
  generate_json: true

neuron_types:
  # Example neuron types for optic-lobe dataset
  - name: "LC10a"
    description: "Lobula Columnar 10a"
    query_type: "type"
  - name: "LC4"
    description: "Lobula Columnar 4"
    query_type: "type"
  - name: "LPLC2"
    description: "Lobula Plate Lobula Columnar 2"
    query_type: "type"
    soma_side: "both"
    min_synapse_count: 10

html:
  title_prefix: "Neuron Type Report"
  css_framework: "plume"  # Using Plume CSS framework
  include_images: true
  include_connectivity: true
