[project]
name = "quickpage"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.11"
click = "*"
jinja2 = "*"
pyyaml = "*"
requests = "*"
pandas = "*"
toml = "*"
pip = "*"

[pypi-dependencies]
quickpage = { path = ".", editable = true }
neuprint-python = "*"

[tasks]
dev = "python -m quickpage --help"
generate = "python -m quickpage generate"
install = "pip install -e ."
