[project]
authors = [{name = "Frank Loesche", email = "loeschef@janelia.hhmi.org"}]
dependencies = [
    "click>=8.0.0",
    "jinja2>=3.0.0",
    "pyyaml>=6.0",
    "requests>=2.28.0",
    "pandas>=1.5.0",
    "neuprint-python>=0.4.0",
    "toml>=0.10.0"
]
name = "quickpage"
requires-python = ">= 3.11"
version = "0.1.0"

[project.scripts]
quickpage = "quickpage.cli:main"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
python = ">=3.11"
click = "*"
jinja2 = "*"
pyyaml = "*"
requests = "*"
pandas = "*"
toml = "*"
pip = "*"

[tool.pixi.pypi-dependencies]
quickpage = { path = ".", editable = true }

[tool.pixi.tasks]
dev = "python -m quickpage --help"
generate = "python -m quickpage generate"
install = "pip install -e ."
