# QuickPage Configuration
neuprint:
  server: "neuprint-cns.janelia.org"
  dataset: "cns"

output:
  directory: "output"
  template_dir: "templates"
  # Additional output settings

# Auto-discovery settings for neuron types
discovery:
  # Number of neuron types to select and generate pages for
  max_types: 10
  # Pattern to filter neuron types (regex, optional)
  type_filter: ""
  # Exclude these neuron types (exact matches)
  exclude_types: []
  # Include only these specific types (if specified, overrides discovery)
  include_only: []
  # Randomize selection (true) or use alphabetical order (false)
  randomize: true

html:
  title_prefix: "Male CNS Cell Type Explorer v2.5"

test_neuron_types:
  normal-set:
    - "SAD103"
    - "SAD052"
    - "Tm3"
    - "SIP071"
    - "AOTU019"
    - "AVLP346"
    - "IN08A006"
    - "SNta35"
    - "'Tergotr. MN'"
    - "'Tergopleural/Pleural promotor MN'"
    - "'IN20A.22A070,IN20A.22A080'"
    - "'PEN_b(PEN2)'"
    - "AN07B013"
    - "'AN08B059'"
    - "'AVLP727m'"
    - "'AOTU103m'"
    - '"KCa''b''-ap1"'
    - "'Acc. ti flexor MN'"
  small-set:
    - "SAD103"
    - "Tm3"
    - "AOTU019"
