# QuickPage Configuration
neuprint:
  server: "neuprint-cns.janelia.org"
  dataset: "flywire-fafb:v783b"

output:
  directory: "output"
  template_dir: "templates"
  # Additional output settings
  include_3d_view: true

# Auto-discovery settings for neuron types
discovery:
  # Number of neuron types to select and generate pages for
  max_types: 10
  # Pattern to filter neuron types (regex, optional)
  type_filter: ""
  # Exclude these neuron types (exact matches)
  exclude_types: []
  # Include only these specific types (if specified, overrides discovery)
  include_only: []
  # Randomize selection (true) or use alphabetical order (false)
  randomize: true

html:
  title_prefix: "FAFB Cell Type Explorer v2.4"
  css_framework: "plume" # Using Plume CSS framework
  include_images: true

# Test neuron types for this dataset
test_neuron_types:
  normal-set:
    - "Tm3"
    - "AOTU019"
    - "L1"
    - "CB0674"
  small-set:
    - "L1"
    - "Tm1"
    - "Mi1"
