# neuView Configuration
neuprint:
  server: "neuprint.janelia.org"
  dataset: "male-cns:v0.9"

output:
  directory: "output"
  template_dir: "templates"
  # Additional output settings

neuroglancer:
  base_url: "https://neuroglancer-demo.appspot.com/"

# Auto-discovery settings for neuron types
discovery:
  # Number of neuron types to select and generate pages for
  max_types: 10
  # Pattern to filter neuron types (regex, optional)
  type_filter: ""
  # Exclude these neuron types (exact matches)
  exclude_types: []
  # Include only these specific types (if specified, overrides discovery)
  include_only: []
  # Randomize selection (true) or use alphabetical order (false)
  randomize: true

html:
  title_prefix: "Male CNS"
  github_repo: "https://github.com/reiserlab/celltype-explorer-drosophila-male-cns"
  youtube_channel: "https://www.youtube.com/@ReiserLab"

test_neuron_types:
  normal-set:
    - "SAD103"
    - "SAD052"
    - "Tm3"
    - "SIP071"
    - "AOTU019"
    - "AVLP346"
    - "IN08A006"
    - "SNta35"
    - "'Tergotr. MN'"
    - "'Tergopleural/Pleural promotor MN'"
    - "'IN20A.22A070,IN20A.22A080'"
    - "'PEN_b(PEN2)'"
    - "AN07B013"
    - "'AN08B059'"
    - "'AVLP727m'"
    - "'AOTU103m'"
    - '"KCa''b''-ap1"'
    - "'Acc. ti flexor MN'"
  small-set:
    - "SAD103"
    - "Tm3"
    - "AOTU019"
